version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      -  ./data:/var/lib/postgresql/data

  bot:
    image: summer_lessons
    environment: 
      CREATE_TABLE: 'yes'
      DB_SWITCH: 'on'
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
    ports:
      - "80:8080" 